version: "3.3"
services:
  network:
    build: command/network/.
    ports: 
      - "8000:8000"
  controller:
    build: command/controller/.
  mysaarc:
    build: command/mysaarc/.
    ports:
      - "8765:8765"