version: "3.3"
services:
  master:
    image: registry.bentley.sh/jn/master:latest
    environment:
      - "ROS_IP=172.10.0.100"
    ports:
      - 11311:11311
    networks:
      ros_net:
        ipv4_address: 172.10.0.100

  openni:
    image: registry.bentley.sh/jn/openni:latest
    devices:
      - /dev/bus/usb/001:/dev/bus/usb/001
    environment:
      - "ROS_IP=172.10.0.101"
      - "ROS_MASTER_URI=http://172.10.0.100:11311"
    networks:
      ros_net:
        ipv4_address: 172.10.0.101
    depends_on:
      - "master"

  rtabmap:
    image: registry.bentley.sh/jn/rtabmap:latest
    environment:
      - "ROS_IP=172.10.0.102"
      - "ROS_MASTER_URI=http://172.10.0.100:11311"
    networks:
      ros_net:
        ipv4_address: 172.10.0.102
    restart: always
    depends_on:
      - "master"

  controller:
    image: registry.bentley.sh/jn/controller:latest

  stm:
    image: registry.bentley.sh/jn/stm:latest

networks:
  ros_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.10.0.0/24