version: "3.3"
services:
  master:
    image: registry.bentley.sh/jn/master:latest
    restart: always
    ports:
      - 11311:11311
    networks:
      # internet:
      ros_net:
        ipv4_address: 172.10.0.100

  openni:
    image: registry.bentley.sh/jn/openni:latest
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - "ROS_IP=172.10.0.101"
      - "ROS_MASTER_URI=http://172.10.0.100:11311"
    restart: always
    networks:
      ros_net:
        ipv4_address: 172.10.0.101
    depends_on:
      - "master"

  rtabmap:
    image: registry.bentley.sh/jn/rtabmap:latest
    environment:
      - "ROS_IP=172.10.0.102"
      - "ROS_MASTER_URI=http://172.10.0.100:11311"
    networks:
      ros_net:
        ipv4_address: 172.10.0.102
    restart: always
    profiles:
      - mapping
    depends_on:
      - "master"
      - "openni"

  web-video:
    image: registry.bentley.sh/jn/web/video:latest
    environment:
      - "ROS_IP=172.10.0.103"
      - "ROS_MASTER_URI=http://172.10.0.100:11311"
    networks:
      ros_net:
        ipv4_address: 172.10.0.103
      # internet:
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - "openni"

  tf:
    image: registry.bentley.sh/jn/tf:latest
    environment:
      - "ROS_IP=172.10.0.104"
      - "ROS_MASTER_URI=http://172.10.0.100:11311"
    networks:
      ros_net:
        ipv4_address: 172.10.0.104

  web-ui:
    image: registry.bentley.sh/jn/web/ui:latest
    ports:
      - 80:80
    networks:
      - ros_net

  command-follower:
    image: registry.bentley.sh/jn/command/follower:latest
    environment:
      - "ROS_MASTER_URI=http://172.10.0.100:11311"
    networks:
      - ros_net

  command-network:
    image: registry.bentley.sh/jn/command/network:latest
    networks:
      - ros_net

  command-mysaarc:
    image: registry.bentley.sh/jn/command/mysaarc:latest
    ports:
      - 8765:8765
    networks:
      - ros_net

  flasher:
    privileged: true
    image: registry.bentley.sh/stm/flasher:latest
    profiles:
      - update

networks:
  ros_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.10.0.0/24
        gateway: 100.109.227.45

  # internet:
  #   driver: bridge
  #   ipam:
  #     driver: default
  #     config:
  #     - subnet: 172.11.0.0/24

